### ISSUE TITLE
ClassDB.PostgresLog is not temporary (W)

### ISSUE THREAD

**Issue by srrollo** [DASSL/ClassDB#162] opened 2018-01-12 20:52 UTC
`ClassDB.PostgresLog` is not created as a temporary table, however its use is strictly temporary - it is filled and then truncated withing `importConnectionLog()` only. It should be created as a temporary table within `importConnectionLog()`.

**Comment by smurthys** [comment] 2018-06-07 10:14
It seems this is a duplicate of #204 (my fault creating 204).

I am closing this issue because #204 already has some metadata associated.

**Closed by smurthys** 2018-06-07 10:14 UTC
Labels: duplicate, priority medium, wrong
